#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@aria2[-1]
	set ucitrack.aria2="aria2"
	set ucitrack.aria2.init='Aria2_Config'
	commit ucitrack
EOF
chmod 755 /etc/init.d/Aria2_Init
/etc/init.d/Aria2_Init enabled && {
	/etc/init.d/Aria2_Init stop
	/etc/init.d/Aria2_Init disable
}
rm -f /tmp/luci-indexcache
exit 0
