#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@aria2[-1]
	set ucitrack.aria2="aria2"
	set ucitrack.aria2.init='aria2'
	commit ucitrack
EOF
chmod 755 /etc/init.d/aria2
rm -f /tmp/luci-indexcache
exit 0
