#!/bin/sh
# Author : RA <ravageralpha@gmail.com>

[ -z `which wget` ] && echo "No wget detected,please install first" && exit 1
[ -n `which openssl` ] && BASE64='openssl base64'
[ -n `which base64` ] && BASE64='base64'
[ -z "$BASE64" ] && echo "No base64/Openssl tools detected,please install first" && exit 1

JSONPATH="http://192.168.1.1:6800/jsonrpc"

usage() {
	echo "Usage:
	-add [url]\t\tadd task
	-addTorrent [file]\tadd BitTorrent task
	-pause\t\t\tpause all task
	-resume\t\t\tresume all task
	-status\t\t\tget global status"
}

[ $# -eq 0 ] && usage

if [ $# -ge 1 ]; then

	case "$1" in
		'-add')
			json="{\"jsonrpc\":\"2.0\", \"id\":\"RA\", \"method\":\"aria2.addUri\", \"params\":[[\""$2"\"]]}"
			;;
		'-addTorrent')
			json="{\"jsonrpc\":\"2.0\", \"id\":\"RA\", \"method\":\"aria2.addTorrent\", \"params\":[\""`cat $2 | "$BASE64"`"\"]}"
			;;
		'-pause')
			json="{\"jsonrpc\":\"2.0\", \"id\":\"RA\", \"method\":\"aria2.pauseAll\"}"
			;;
		'-resume')
			json="{\"jsonrpc\":\"2.0\", \"id\":\"RA\", \"method\":\"aria2.unpauseAll\"}"
			;;
		'-status')
			json="{\"jsonrpc\":\"2.0\", \"id\":\"RA\", \"method\":\"aria2.getGlobalStat\"}"
			;;
		*)
			usage
			exit 1
	esac

	result=$(wget -qO- --header="Content-Type: application/json" --post-data="$json" "$JSONPATH")
	if [ -n "$result" ]; then
		case "$1" in
			-status)

				rawdata=$(echo "$result" | awk -F 'result":' '{print $2}' | sed -e 's/["{}]//g' | awk -v RS="," '{print}' | awk -F ':' '{print $2}')

				DOWNLOADSPEED="$(($(echo "$rawdata" | sed -n 1p)/1024))K"
				UPLOADSPEED="$(($(echo "$rawdata" | sed -n 5p)/1024))K"
				ActivedTask=$(echo "$rawdata" | sed -n 2p)
				WaitingTask=$(echo "$rawdata" | sed -n 4p)

				echo "DownloadSpeed:$DOWNLOADSPEED"
				echo "UploadSpeed:$UPLOADSPEED"
				echo "ActiveTask:$ActivedTask"
				echo "WaitingTask:$WaitingTask"
				;;
			*)
				echo "Successful"
				;;
		esac
	else
		echo "Fail"
	fi
fi
