#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || {
	( . /etc/uci-defaults/luci-RSS ) && rm -f /etc/uci-defaults/luci-RSS
	chmod 755 /etc/init.d/RSS >/dev/null 2>&1
	/etc/init.d/RSS enable >/dev/null 2>&1
	exit 0
}
